//HintName: TestNamespace_ITestClass__.g.cs
// <auto-generated />
namespace TestNamespace
{
	public interface ITestClass<T1, T2, T3>
	{
		T3 TetMethod(T2 p);
		T1 TestProp { get; set; }
	}

	public partial class TestClass<T1, T2, T3> : ITestClass<T1, T2, T3>
	{
	}
}