//HintName: TestNamespace_ITestRecordClass__.g.cs
// <auto-generated />
namespace TestNamespace
{
	public interface ITestRecordClass
	{
		string TestMethod();
		int TestProp { get; set; }

		event global::System.EventHandler TestEvent;
		int this[string a] { get; }
	}

	public partial record class TestRecordClass : ITestRecordClass;
}