//HintName: TestNamespace_IPublicService__.g.cs
// <auto-generated />
namespace TestNamespace
{
	public interface IPublicService
	{
		global::System.Exception PrivateGetSetProperty { init; }

		int FullyPublicProperty { get; set; }

		string PublicGetterPrivateSetter { get; }

		global::System.Collections.Generic.IEnumerable<string> PrivateGetterPublicSetter { set; }
	}

	public partial record struct PublicService : IPublicService;
}