//HintName: TestNamespace_ITestStruct__.g.cs
// <auto-generated />
namespace TestNamespace
{
	public interface ITestStruct
	{
		string TestMethod();
		int TestProp { get; set; }

		event global::System.EventHandler TestEvent;
		int this[string a] { get; }
	}

	public partial struct TestStruct : ITestStruct
	{
	}
}