//HintName: Teikei_Interfaced__.g.cs
// <auto-generated />
namespace Teikei
{
	[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false)]
	internal class InterfacedAttribute : System.Attribute
	{
		public InterfacedAttribute(bool SkipOverlappingMembers = true, bool ForcePublicAccessibility = false)
		{
		}
	}
}