//HintName: TestNamespace_ITestClass__.g.cs
// <auto-generated />
namespace TestNamespace
{
	public interface ITestClass
	{
		event global::System.EventHandler Test1;
		event global::System.EventHandler<int> Test2;
	}

	public partial class TestClass : ITestClass
	{
	}
}