//HintName: TestNamespace_ITestClass__.g.cs
// <auto-generated />
namespace TestNamespace
{
	/// <summary>
	/// Test class unlike any you've evere seen
	/// </summary>
	public interface ITestClass
	{
		/// <summary>
		/// did you notice there's a typo in this method's name?
		/// </summary>
		/// <returns>look at implementation and make a guess</returns>
		bool TetMethod(int p);
		/// <summary>
		/// Best property EU
		/// </summary>
		int TestProp { get; set; }

		/// <summary>
		/// I wish for observables to phase out events
		/// </summary> 
		event global::System.EventHandler TestEvent;
		/// <summary>
		/// Does anyone actually use documentation comments on indexers?
		/// </summary>
		int this[string a] { get; }
	}

	public partial class TestClass : ITestClass
	{
	}
}