//HintName: TestNamespace_TestNamespace.TestClass_GenerateSut_Base__.g.cs
// <auto-generated />
namespace TestNamespace
{
	public partial class TestClass
	{
		private partial global::TestNamespace.SutClass GenerateSut()
		{
			return new global::TestNamespace.SutClass();
		}
	}
}