//HintName: Teikei_GenerateSut__.g.cs
// <auto-generated />
namespace Teikei
{
	[System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]
	internal class GenerateSutAttribute : System.Attribute
	{
	}
}